### PR TITLE
adding jupyter notebook mathjax config

### PR DESCRIPTION
**Pull request by choldgraf**
This adds the default notebook mathjax config as a little javascript file.

@phaustin @chrisjsewell think this will fix the problem?

closes https://github.com/ExecutableBookProject/MyST-NB/issues/99

### CODE REVIEW

**Comment by phaustin** [comment]
Trying to test this, but I've hit a snag at the ipynb stage.  Can someone confirm that 

```
$$
\begin{align}
\frac{\partial v}{\partial t} + u \frac{\partial v}{\partial x} + v \frac{\partial v}{\partial y} + w \frac{\partial v}{\partial z} + fu = - \, \frac{1}{\rho} \, \frac{\partial p}{\partial y}
+ A_v \, \frac{\partial^2 v}{\partial z^2} + A_h \, \nabla^2 v
\end{align}
$$
```
works in jupyter?   The jupyter parser adds a nested equation environment that mathjax chokes on.

**Comment by choldgraf** [comment]
Yep, just tried it and it works OK

**Comment by phaustin** [comment]
ok -- must be the latex notebook extension I've installed in jupyter that's getting in the way

**Comment by choldgraf** [comment]
OK cool - I'm gonna merge this away and we can spot-check bugs if they come up

**Pull request merged**
