### PR TITLE
Documentation for unit testing

### PR DESCRIPTION
**Pull request by AakashGfude**
@choldgraf @chrisjsewell, have added a few lines on unit testing. What do you think about this? Should I make it more/less verbose? Should I also write about using `mock_document`, `MockEnv`?

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Should I also write about using `mock_document`, `MockEnv`?

FYI in #107 I have removed these, and the tests now run as actual sandboxed sphinx builds. You might be interested to check it out.
This doesn't change what you have already written though, which looks fine 👍

**Comment by choldgraf** [comment]
nice! agreed that this is an improvement. @chrisjsewell if you think we're moving away from `MockFoo`, then I think we can leave it out of the docs. As an aside, I think it's a simpler approach *not* so use these MockEnvs...it feels a little bit brittle since we aren't testing in the *actual* environment that Sphinx has when it runs.

**Comment by chrisjsewell** [comment]
Well there’s a hierarchy of testing; where possible there should be low-level isolated tests per function, then other full scale integration tests. 
But yeh, for this package the MockEnv was getting to complex, so has been removed.

**Comment by choldgraf** [comment]
@chrisjsewell I agree - I just meant that when you're close to Mocking the entirety of a sphinx build, it makes sense to just use the whole sphinx build 😆

**Pull request merged**
