### PR TITLE
Move to codecov

### PR DESCRIPTION
**Pull request by chrisjsewell**
Coveralls doesn't support GitHub actions properly for forked PRs 😒 coverallsapp/github-action#30

https://github.com/codecov/codecov-action

### CODE REVIEW

**Comment by chrisjsewell** [comment]
Coveralls doesn't support GitHub actions properly for forked PRs 😒 coverallsapp/github-action#30

**Comment by chrisjsewell** [comment]
Feeeeeeeck!!!

I can't get this damn thing to work; all you need to do is output the coverage report as XML:

```console
$ pytest --cov=myst_nb --cov-report=xml
================================================================================================= test session starts ==================================================================================================
platform darwin -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.0
rootdir: /Users/cjs14/GitHub/MyST-NB-actual, inifile: pytest.ini
plugins: cov-2.8.1, datadir-1.3.1, regressions-2.0.0
collected 33 items                                                                                                                                                                                                     

tests/test_execute.py ...........                                                                                                                                                                                [ 33%]
tests/test_glue.py ......                                                                                                                                                                                        [ 51%]
tests/test_nb_render.py ...........                                                                                                                                                                              [ 84%]
tests/test_parser.py ..                                                                                                                                                                                          [ 90%]
tests/test_text_based.py .                                                                                                                                                                                       [ 93%]
tests/test_transform.py ..                                                                                                                                                                                       [100%]

---------- coverage: platform darwin, python 3.7.6-final-0 -----------
Coverage XML written to file coverage.xml
```

But then `coverage.xml` is nowhere to be found!? It's the same with `--cov-report=html`, and I know for certain that I have had that working before, so it must be something to do with the current package versions or something?

**Comment by chrisjsewell** [comment]
Also this is working fine in my aiida development environment:

```
$ conda list
...
coverage                  4.5.4            py37h0b31af3_0    conda-forge
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
```

**Comment by chrisjsewell** [comment]
Ok! for some reason the `tests/conftest.py::check_nbs` fixture breaks pytest-cov's cov-report outputting. I notice that multiple `.coverage` files are being created, then merged, so I imagine its something to do with this. Anyway, I've added `coverage xml` after pytest and that seems to do the job

**Comment by AndreMiras** [comment]
FYI I got it working and recently wrote a GitHub Action for it https://github.com/marketplace/actions/coveralls-python

**Pull request merged**
