### PR TITLE
Added a copy method to celloutputbundlenode

### PR DESCRIPTION
**Pull request by AakashGfude**
Added a copy method which also takes `outputs` as argument

fixes https://github.com/ExecutableBookProject/MyST-NB/issues/151

### CODE REVIEW

**Comment by choldgraf** [comment]
Is this something that we could add a test for?

**Comment by AakashGfude** [comment]
@choldgraf we can test this as a part of a `latex` build in `test_transform`?

**Comment by choldgraf** [comment]
sure - I just wanna make sure that the bug we think we are fixing doesn't re-surface :-)

**Comment by AakashGfude** [comment]
Hey @choldgraf , what do you think about the test added?

**Comment by choldgraf** [comment]
it looks good to me - is it a test that would have failed w/o the `copy` method?

**Comment by AakashGfude** [comment]
@choldgraf , yes it would not have been able to replace `<CelloutputBundleNode>` with specific mime-type nodes.

**Comment by choldgraf** [comment]
Great - I'll merge tomorrow AM unless somebody else suggests otherwise 👍 nice job @AakashGfude !

**Pull request merged**
