### PR TITLE
Move to markdown-it-py markdown parser implementation

### PR DESCRIPTION
**Pull request by chrisjsewell**
Using an alpha release of ExecutableBookProject/MyST-Parser#123

All the current tests pass, with no changes to the expected outputs. I also took the opportunity to split up the code in `NotebookParser.parse` in to separate functions.

### CODE REVIEW

**Comment by chrisjsewell** [comment]
From a quick scan of the documentation, I don't see any issues.

However, I do note that the plotly and ipywidgets no longer show, moving from:

- https://myst-nb.readthedocs.io/en/stable/use/interactive.html
- https://myst-nb.readthedocs.io/en/latest/use/interactive.html

I assume this is because this notebook is now being executed during the build, and is thus encountering  jupyter/nbclient#39

**Comment by chrisjsewell** [comment]
In 74cf6a3 I have introduced some nice, self-documenting render tests, see tests/nb_fixtures/basic.txt

**Comment by chrisjsewell** [comment]
In 536a1dd I have added a simple fix for cell index / line number reporting:

Line number are now set as `<cell index>*10000 + <line number>` (I'm guessing a cell won't have more than 10000 lines!). This is a simple solution to addresses #71, that doesn't require any complex overrides of the sphinx reporting machinery.  We should also document this.

**Comment by choldgraf** [comment]
I think this looks great, and agreed about the widgets not showing up. I don't think that should block us here

**Pull request merged**
